import { APPOINTMENT_STATUS } from './APPOINTMENT_STATUS';

export const EVENT_COLOR = {
  [APPOINTMENT_STATUS.SCHEDULED]: '#3B82F6',
  [APPOINTMENT_STATUS.CONFIRMED]: '#10B981',
  [APPOINTMENT_STATUS.WAITING_CONSULTATION]: '#38bdf8',
  [APPOINTMENT_STATUS.IN_CONSULTATION]: '#84cc16',
  [APPOINTMENT_STATUS.COMPLETED]: '#71717A',
  [APPOINTMENT_STATUS.CANCELED]: '#EF4444',
  [APPOINTMENT_STATUS.NO_SHOW]: '#94a3b8',
};
