export const PERMISSIONS = {
  PATIENT_VIEW: 'PATIENT_VIEW',
  PATIENT_CREATE: 'PATIENT_CREATE',
  PATIENT_UPDATE: 'PATIENT_UPDATE',

  APPOINTMENT_VIEW: 'APPOINTMENT_VIEW',
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_RESCHEDULE: 'APPOINTMENT_RESCHEDULE',
  APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',
  APPOINTMENT_MANAGE_STATUS: 'APPOINTMENT_MANAGE_STATUS',

  CONSULT_VIEW: 'CONSULT_VIEW',
  CONSULT_START: 'CONSULT_START',
  CONSULT_UPDATE: 'CONSULT_UPDATE',
  CONSULT_FINISH: 'CONSULT_FINISH',

  CLINIC_USER_VIEW: 'CLINIC_USER_VIEW',
  CLINIC_USER_MANAGE: 'CLINIC_USER_MANAGE',
  CLINIC_USER_PRICE_MANAGE: 'CLINIC_USER_PRICE_MANAGE',

  FINANCIAL_VIEW: 'FINANCIAL_VIEW',
  FINANCIAL_CREATE: 'FINANCIAL_CREATE',
  FINANCIAL_UPDATE: 'FINANCIAL_UPDATE',
} as const;

export type TPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
